server:
  port: 8085
  error:
    include-stacktrace: never
    include-message: always

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.value.default.type: com.rahul.notificationservice.kafka.event.BookingConfirmedEvent
        spring.json.use.type.headers: false
        spring.json.trusted.packages: com.rahul.notificationservice.kafka.event


