server:
  port: 8084
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/paymentdb
    username: ticketuser
    password: ticketpass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

payment:
  max-amount: 1000

logging:
  level:
    root: INFO
    com.rahul.paymentservice: DEBUG
