server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: ticketuser
    password: ticketpass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  expiration-minutes: 15
  refresh-expiration-days: 7

app:
  seed-dev-users: true

logging:
  level:
    root: INFO
    com.rahul.userservice: DEBUG
