server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: ticketuser
    password: ticketpass
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  expiration-minutes: 15
  refresh-expiration-days: 7

login-limit:
  max-attempts: 5
  window-seconds: 60

logging:
  level:
    root: INFO
    com.rahul.userservice: DEBUG